import type { Payload } from 'payload'

export async function seedHomeGlobal(payload: Payload, heroImageId: string, aboutImageId: string, ctaImageId: string) {
  await payload.updateGlobal({
    slug: 'home',
    data: {
      layout: [
        {
          blockType: 'homeSectionHero',
          titlePart1: 'Sites que ',
          titleAccent1: 'gritam',
          titlePart2: 'negócios que ',
          titleAccent2: 'escalam.',
          description:
            'Estúdio digital especializado em WordPress, e-commerce e produtos web sob medida. Construímos com leveza, código limpo e atenção a quem importa: o seu cliente.',
          cta1Label: 'Quero um orçamento',
          cta1Href: '#',
          cta2Label: 'Ver portfólio',
          cta2Href: '#',
          image: heroImageId,
        },
        {
          blockType: 'homeSectionLogoCloud',
          eyebrow: 'Clientes',
          titleStart: 'Empresas que ',
          titleAccent: 'confiam',
          titleEnd: ' na gente',
          description:
            'Marcas que caminham com a gente — do primeiro briefing à manutenção recorrente. Pequenos negócios e times grandes, mesmo cuidado.',
          partners: [
            { name: 'Quintal Bistrô', glyph: 'circle' },
            { name: 'Thrive', glyph: 'triangle' },
            { name: 'Xfive Studio', glyph: 'square' },
            { name: 'Bukuji', glyph: 'diamond' },
            { name: 'Gridl', glyph: 'arc' },
            { name: 'Empório Raízes', glyph: 'plus' },
            { name: 'Bossanova', glyph: 'hexagon' },
            { name: 'Tecnocafé', glyph: 'rings' },
            { name: 'Folha & Pedra', glyph: 'halfcircle' },
            { name: 'Movimento Verde', glyph: 'wave' },
            { name: 'Casa Lila', glyph: 'chevron' },
            { name: 'Norte Estúdio', glyph: 'bars' },
          ],
        },
        {
          blockType: 'homeSectionServices',
          eyebrow: 'Serviços',
          titleStart: 'Soluções ',
          titleAccent: 'inteligentes',
          titleEnd: '\npara o seu negócio',
          description:
            'Da estratégia ao código. A gente entrega o pacote completo — ou se encaixa onde seu time precisa de reforço.',
          services: [
            {
              name: 'WordPress sob medida',
              variant: 'blue',
              description: 'Tema 100% próprio, painel editável e suporte mensal incluso.',
              iconType: 'globe',
              ctaLabel: 'Conheça',
              ctaHref: '#',
            },
            {
              name: 'E-Commerce',
              variant: 'orange',
              description: 'WooCommerce, integrações com ERP, checkout que converte.',
              iconType: 'cart',
              ctaLabel: 'Conheça',
              ctaHref: '#',
            },
            {
              name: 'Landing Pages',
              variant: 'blue',
              description: 'LPs de conversão com A/B test, copy e analytics ligados.',
              iconType: 'landing',
              ctaLabel: 'Conheça',
              ctaHref: '#',
            },
            {
              name: 'UX/UI Design',
              variant: 'orange',
              description: 'Pesquisa, fluxos, wireframes e protótipos navegáveis.',
              iconType: 'screen',
              ctaLabel: 'Conheça',
              ctaHref: '#',
            },
            {
              name: 'Branding',
              variant: 'blue',
              description: 'Identidade, naming, manual e aplicações da marca.',
              iconType: 'brand',
              ctaLabel: 'Conheça',
              ctaHref: '#',
            },
            {
              name: 'Soluções Digitais',
              variant: 'orange',
              description: 'Sistemas, dashboards e automações sob medida.',
              iconType: 'code',
              ctaLabel: 'Conheça',
              ctaHref: '#',
            },
          ],
        },
        {
          blockType: 'homeSectionAbout',
          eyebrow: 'Sobre nós',
          titlePart1: 'Um estúdio ',
          titleAccent1: 'pequeno',
          titlePart2: ' com\nentregas ',
          titleAccent2: 'de gente grande.',
          description:
            'Somos um time enxuto de design e desenvolvimento, baseado em Sorocaba (SP), entregando para clientes do Brasil inteiro desde 2017. Trabalhamos com agendas tranquilas e dedicação real — você fala com o mesmo time do briefing ao go-live.',
          ctaLabel: 'Conheça o time',
          ctaHref: '#',
          features: [
            {
              title: 'Sem terceirização',
              description: 'Quem desenha é quem entrega. Sem caixa-preta, sem repasse.',
            },
            {
              title: 'Cronograma realista',
              description: 'Prazo combinado é prazo cumprido. Sem promessa que não cabe.',
            },
            {
              title: 'Transparência total',
              description: 'Você acompanha o board do projeto em tempo real.',
            },
            {
              title: 'Suporte que responde',
              description: 'Após o go-live a gente continua de plantão por 30 dias.',
            },
          ],
          image: aboutImageId,
        },
        {
          blockType: 'homeSectionProjects',
          eyebrow: 'Trabalhos recentes',
          titleStart: 'Projetos que ',
          titleAccent: 'colocamos pra rodar',
          portfolioLabel: 'Ver portfólio completo',
          portfolioHref: '#',
          projects: [
            {
              tag: 'E-Commerce',
              tagVariant: 'orange',
              accent: 'orange',
              client: 'Quintal Bistrô',
              year: '2025',
              title: 'Cardápio digital com integração POS',
              result: '+38% ticket médio',
              motifType: 'tagMark',
              href: '#',
            },
            {
              tag: 'UX/UI',
              tagVariant: 'blue',
              accent: 'blue',
              client: 'Gridl Design',
              year: '2024',
              title: 'Dashboard de gestão para agência',
              result: '−42% cliques por tarefa',
              motifType: 'dashboard',
              href: '#',
            },
            {
              tag: 'Landing Page',
              tagVariant: 'orange',
              accent: 'orange',
              client: 'Xfive Studio',
              year: '2025',
              title: 'Lançamento SaaS — campanha de pré-venda',
              result: '7,2% de conversão',
              motifType: 'arrowCurve',
              href: '#',
            },
          ],
        },
        {
          blockType: 'homeSectionProcess',
          eyebrow: 'Como trabalhamos',
          titleStart: 'Um ',
          titleAccent: 'processo claro',
          titleEnd: ', do briefing ao go-live',
          description:
            'Cinco passos que repetimos em todo projeto. Você sabe sempre onde a gente está, o que vem depois e o que precisa de você.',
          highlightIndex: 2,
          steps: [
            { title: 'Descobrir', description: 'Entrevistas, contexto e benchmark.' },
            { title: 'Definir', description: 'Escopo, MVP e prioridades.' },
            { title: 'Desenhar', description: 'UX, UI e protótipo navegável.' },
            { title: 'Desenvolver', description: 'Código, testes e integrações.' },
            { title: 'Decolar', description: 'Go-live, treino e suporte.' },
          ],
        },
        {
          blockType: 'homeSectionStats',
          showDecoration: true,
          stats: [
            { value: '+120', label: 'Projetos entregues' },
            { value: '8 anos', label: 'No digital' },
            { value: '94 NPS', label: 'Média pós-projeto' },
            { value: '+38%', label: 'Conversão média' },
          ],
        },
        {
          blockType: 'homeSectionTestimonials',
          eyebrow: 'Depoimentos',
          titleStart: 'Quem trabalhou com a gente ',
          titleAccent: 'volta',
          description:
            '70% do nosso faturamento vem de clientes recorrentes ou indicação direta. Não é por acaso.',
          ratingValue: '4,9 / 5,0',
          reviewCount: '47 avaliações no Google',
          testimonials: [
            {
              quote:
                'O time da GritoWeb entendeu nossa operação antes de abrir o Figma. O painel ficou tão claro que nem precisei treinar a equipe.',
              author: 'Marina Prado',
              role: 'Diretora de Marketing — Quintal Bistrô',
              avatarVariant: 'blue',
              surface: 'paper',
            },
            {
              quote:
                'Em 6 meses triplicamos o MRR do clube de assinatura. O e-commerce não engasga mais e nosso financeiro virou um botão.',
              author: 'Caio Bertoni',
              role: 'CEO — Empório Raízes',
              avatarVariant: 'orange',
              surface: 'card',
            },
          ],
        },
        {
          blockType: 'homeSectionBlog',
          eyebrow: 'Do nosso blog',
          titleStart: 'Ideias que ',
          titleAccent: 'colocam',
          titleEnd: ' seu negócio pra correr',
          blogLabel: 'Ler todos os artigos',
          blogHref: '#',
          posts: [
            {
              tag: 'WordPress',
              tagVariant: 'blue',
              date: '18 · Abr · 2026',
              title: 'Como preparar seu WordPress para escalar sem quebrar',
              excerpt:
                'Checklist prático para negócios que cresceram mais rápido que a arquitetura do site.',
              href: '#',
            },
            {
              tag: 'UX/UI',
              tagVariant: 'orange',
              date: '05 · Abr · 2026',
              title: 'Tom de voz digital: por que "leve" vende mais que "premium"',
              excerpt:
                'Estudo com 12 LPs brasileiras mostra como proximidade bate autoridade.',
              href: '#',
            },
            {
              tag: 'Processo',
              tagVariant: 'blue',
              date: '07 · Mar · 2026',
              title: 'Briefing que salva projeto: 14 perguntas antes do Figma',
              excerpt:
                'A pauta que usamos em todo kickoff para mapear 80% das dores logo de cara.',
              href: '#',
            },
          ],
        },
        {
          blockType: 'homeSectionCta',
          variant: 'orange',
          eyebrow: 'Próximo passo',
          titleMain: 'Tem um projeto',
          titleSecondary: 'em mente?',
          titleSecondaryColor: 'blue',
          description:
            'Conta pra gente em duas linhas o que você precisa. Devolvemos uma proposta em 3 dias úteis.',
          cta1Label: 'Agendar uma call',
          cta1Href: '#',
          cta1Variant: 'blue',
          cta2Label: 'Baixar portfólio (PDF)',
          cta2Href: '#',
          cta2Variant: 'white',
          image: ctaImageId,
        },
        {
          blockType: 'homeSectionContact',
          email: 'contato@gritoweb.com',
          emailHref: 'mailto:contato@gritoweb.com',
          phone: '(15) 99739-4486',
          phoneHref: 'tel:+5515997394486',
        },
      ],
    },
  })
}
