export { SectionTitle } from './SectionTitle'
export { HeroSection } from './HeroSection'
export { LogoCloud } from './LogoCloud'
export { AboutSplit, AboutFeatures } from './AboutSplit'
export { ServiceGrid } from './ServiceGrid'
export { ProjectGrid } from './ProjectGrid'
export { PostGrid } from './PostGrid'
export { ProcessTrail } from './ProcessTrail'
export { StatsBand } from './StatsBand'
export { TestimonialsSection } from './TestimonialsSection'
export { CtaBanner } from './CtaBanner'
export { FaleComAGente } from './FaleComAGente'
